services:
  sv-backend-chat:
    image: 'sv-backend-chat'
    build:
      context: .
      dockerfile: Dockerfile-development
    # restart: always
    networks:
      - app-network
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=PathPrefix(`/sv-backend-chat`)'
      - 'traefik.http.routers.api.entrypoints=web'
      - 'traefik.http.routers.api.middlewares=strip-prefix' # เพิ่ม middleware
      - 'traefik.http.middlewares.strip-prefix.stripprefix.prefixes=/sv-backend-chat' # กำหนด prefix ที่จะตัด
      - 'traefik.http.services.api.loadbalancer.server.port=3000'
    volumes:
      - '$PWD:/app'
    environment:
      - NODE_ENV=localhost
      - APP_REGION=th
    command: npm run start:dev

networks:
  app-network:
    external: true
