services:
  sv-backend-chat:
    image: 'sv-backend-chat'
    build:
      context: .
      dockerfile: Dockerfile-development
    # restart: always
    networks:
      - app-network
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=PathPrefix(`/sv-backend-chat`)'
      - 'traefik.http.routers.api.entrypoints=web'
      - 'traefik.http.routers.api.middlewares=strip-prefix' # เพิ่ม middleware
      - 'traefik.http.middlewares.strip-prefix.stripprefix.prefixes=/sv-backend-chat' # กำหนด prefix ที่จะตัด
      - 'traefik.http.services.api.loadbalancer.server.port=3000'
    volumes:
      - '$PWD:/app'
    environment:
      - NODE_ENV=localhost
      - APP_REGION=th
    command: npm run start:dev

    # เพิ่มบริการของ Traefik
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - '--log.level=DEBUG'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entryPoints.web.address=:80'
    ports:
      - '80:80' # การเชื่อมต่อ HTTP
      - '8080:8080' # Dashboard ของ Traefik
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock' # เชื่อมโยง socket ของ Docker
    networks:
      - app-network # ใช้ network เดียวกับบริการอื่นๆ

networks:
  app-network:
    external: true
